version: '3.4'
services:
  db:
    image: tiagosp13/mysql_8
    container_name: mysql_8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
